export const TextsPreparingFood = [
  {
    title: "Preparing Food",
    type: "1- Basic Texts",
    order: 3,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg",
    elements: [
      {
        subtitle: "Practice Vocabulary",
        comments: "Vocabulário adicional para prática.",
        order: 0,
        grid: 2,
        type: "sentences",
        sentences: [
          { english: "Hungry", portuguese: "Com fome" },
          { english: "Kitchen", portuguese: "Cozinha" },
          { english: "Egg", portuguese: "Ovo" },
          { english: "Oil", portuguese: "Óleo" },
          { english: "Skillet", portuguese: "Frigideira" },
          { english: "Stove", portuguese: "Fogão" },
          { english: "Heat", portuguese: "Calor" },
          { english: "Bowl", portuguese: "Tigela" },
          { english: "Stir", portuguese: "Mexer" },
          { english: "Cook", portuguese: "Cozinhar" },
          { english: "Plate", portuguese: "Prato" },
          { english: "Dining room", portuguese: "Sala de jantar" },
          { english: "Chair", portuguese: "Cadeira" },
          { english: "Spoon", portuguese: "Colher" },
          { english: "Soap", portuguese: "Sabão" },
          { english: "Sponge", portuguese: "Esponja" },
          { english: "Damp", portuguese: "Úmido" },
          { english: "Wipe", portuguese: "Limpar" },
          { english: "Table", portuguese: "Mesa" },
          { english: "Watch", portuguese: "Assistir" },
        ],
      },
      {
        subtitle: "Text",
        order: 1,
        type: "text",
        text: "Jack was hungry. He walked to the kitchen. He got out some eggs. He took out some oil. He placed a skillet on the stove. Next, he turned on the heat. He poured the oil into the skillet. He cracked the eggs into a bowl. He stirred the eggs. Then, he poured them into the hot skillet. He waited while the eggs cooked. They cooked for two minutes. He heard them cooking. They popped in the oil. Next, Jack put the eggs on a plate. He placed the plate on the dining room table. They looked pretty on the white plate. He sat down in the large wooden chair. He thought about the day ahead. He ate the eggs with a spoon. They were good. He washed the plate with dishwashing soap. Then, he washed the pan. He got a sponge damp. Finally, he wiped down the table. Next, Jack watched TV.",
      },
      {
        subtitle: "Questions",
        comments: "Tente responder estas perguntas usando o que você aprendeu.",
        order: 2,
        type: "exercise",
        items: [
          "Why did Jack go to the kitchen?",
          "What did Jack do first after getting to the kitchen?",
          "How long did the eggs cook?",
          "What did Jack do after cooking the eggs?",
          "What did Jack think about while eating?",
          "What did Jack do after eating?",
          "How did Jack clean the table?",
          "What did Jack do after cleaning the table?",
          "What did Jack use to eat the eggs?",
        ],
      },
    ],
  },
];
