export const TextsMyWonderfulFamily = [
  {
    title: "My Wonderful Family",
    type: "1- Basic Texts",
    order: 1,
    image:
      "https://cf.ltkcdn.net/family/images/std/200821-800x533r1-family.jpg",
    elements: [
      {
        subtitle: "Practice Vocabulary",
        comments: "Vocabulário adicional para prática.",
        order: 0,
        grid: 2,
        type: "sentences",
        sentences: [
          { english: "Family", portuguese: "Família" },
          { english: "House", portuguese: "Casa" },
          { english: "Mountains", portuguese: "Montanhas" },
          { english: "Brother", portuguese: "Irmão" },
          { english: "Sister", portuguese: "Irmã" },
          { english: "Father", portuguese: "Pai" },
          { english: "Mother", portuguese: "Mãe" },
          { english: "Teacher", portuguese: "Professor" },
          { english: "Nurse", portuguese: "Enfermeira" },
          { english: "Hospital", portuguese: "Hospital" },
          { english: "Smart", portuguese: "Inteligente" },
          { english: "Nervous", portuguese: "Nervosa" },
          { english: "Kind", portuguese: "Gentil" },
          { english: "Grandmother", portuguese: "Avó" },
          { english: "Italy", portuguese: "Itália" },
          { english: "Strong", portuguese: "Forte" },
          { english: "Cook", portuguese: "Cozinhar" },
          { english: "Important", portuguese: "Importante" },
          { english: "Weekend", portuguese: "Fim de semana" },
          { english: "Board game", portuguese: "Jogo de tabuleiro" },
        ],
      },
      {
        subtitle: "Text",
        order: 1,
        type: "text",
        text: "I live in a house near the mountains. I have two brothers and one sister, and I was born last. My father teaches mathematics, and my mother is a nurse at a big hospital. My brothers are very smart and work hard in school. My sister is a nervous girl, but she is very kind. My grandmother also lives with us. She came from Italy when I was two years old. She has grown old, but she is still very strong. She cooks the best food! My family is very important to me. We do lots of things together. My brothers and I like to go on long walks in the mountains. My sister likes to cook with my grandmother. On the weekends we all play board games together. We laugh and always have a good time. I love my family very much.",
      },
      {
        subtitle: "Questions",
        comments: "Tente responder estas perguntas usando o que você aprendeu.",
        order: 2,
        type: "exercise",
        items: [
          "How many siblings does the author have?",
          "What does the author's father do for a living?",
          "Where did the grandmother come from?",
          "What do the author and their brothers like to do together?",
          "Who likes to cook with the grandmother?",
          "What do they do on the weekends?",
          "How does the author describe their sister?",
          "Why is the family important to the author?",
        ],
      },
    ],
  },
];
