export const textsCourse = [
  {
    title: "Saudi Money Helps Make Ronaldo Top Earning Athlete",
    type: "2- Intermediate Texts",
    order: 100,
    // description:
    //   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
    image:
      "https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/7iYuXO0RUVscpjGZnDJfCH.jpeg",
    elements: [
      {
        subtitle: "Practice Vocabulary",
        comments: "Vocabulário adicional para prática.",
        order: 0,
        grid: 2,
        type: "sentences",
        sentences: [
          { english: "Athlete", portuguese: "Atleta" },
          { english: "Career", portuguese: "Carreira" },
          { english: "Magazine", portuguese: "Revista" },
          { english: "Soccer", portuguese: "Futebol" },
          { english: "To Earn", portuguese: "Ganhar/Render" },
          { english: "Earnings", portuguese: "Ganhos" },
          { english: "Tour", portuguese: "Turnê" },
          { english: "Money", portuguese: "Dinheiro" },
          { english: "Player", portuguese: "Jogador" },
          { english: "Reputation", portuguese: "Reputação" },
          { english: "Rival", portuguese: "Rival" },
        ],
      },
      {
        subtitle: "Text",
        order: 1,
        type: "text",
        text: "You might have read that the average age adults stop being cool is 39! Try telling that to Cristiano Ronaldo. The 39-year-old has just been named as the world's highest-paid athlete, for the fourth time in his career. And his fans will tell you that he's as cool as ever!  According to Forbes, the business magazine that publishes a list of the 10 highest-paid athletes, the Portuguese soccer star has earned $260 million over the last 12 months. That's about $8 every second!  Ronaldo moved to play for the Saudi Arabian team Al Nassr in December 2022 and this helped him increase his earnings from $136 million the previous year.  Spanish golfer Jon Rahm is second on the list, and he's also been helped by Saudi Arabian money.  He joined the Saudi-funded LIV Golf tour in December 2023 and he's earned $218 million in the last 12 months.  Soccer players Neymar and Karim Benzema, who both play in Saudi Arabia, are also in the top 10 — in seventh and eighth place.  Saudi Arabia has spent large amounts on bringing some of sport's top events and best athletes to the country.  Some have called it 'sportswashing' — using sport to improve a country's reputation and take attention away from social or environmental problems.  Saudi Arabia doesn't agree. Also in the list of highest earners is Ronaldo's long-time rival, Lionel Messi. He's third with earnings of $135 million. French star Kylian Mbappé is sixth, while there are three basketball players in the top 10: LeBron James, Giannis Antetokounmpo and Stephen Curry.",
      },
      {
        subtitle: "Questions",
        comments: "Tente responder estas pergunta usando o que você aprendeu.",
        order: 2,
        type: "text",
        items: [
          "What are your thoughts on Forbes' list of highest-paid athletes?",
          "Are you a fan of Cristiano Ronaldo? Do you find it surprising that he's the world's highest-paid athlete?",
          "Do you think professional athletes are paid too much?",
          "Who do you imagine are your country's highest-paid athletes?",
          "Which of the athletes mentioned in the article would you most like to meet?",
          "Are you more into soccer, golf, or basketball?",
          "In your opinion, who are the greatest athletes of all time?",
          "Are there any famous athletes that you dislike?",
          "What do you imagine are the hardest things about being a professional athlete?",
          "If you don't believe you are the best, then you will never achieve all that you are capable of. — Cristiano Ronaldo. What do you make of this quote?",
        ],
      },
      {
        subtitle: "Questions",
        comments: "Tente responder estas pergunta usando o que você aprendeu.",
        order: 3,
        type: "exercise",
        items: [
          "What are your thoughts on Forbes' list of highest-paid athletes?",
          "Are you a fan of Cristiano Ronaldo? Do you find it surprising that he's the world's highest-paid athlete?",
          "Do you think professional athletes are paid too much?",
          "Who do you imagine are your country's highest-paid athletes?",
          "Which of the athletes mentioned in the article would you most like to meet?",
          "Are you more into soccer, golf, or basketball?",
          "In your opinion, who are the greatest athletes of all time?",
          "Are there any famous athletes that you dislike?",
          "What do you imagine are the hardest things about being a professional athlete?",
          "If you don't believe you are the best, then you will never achieve all that you are capable of. — Cristiano Ronaldo. What do you make of this quote?",
        ],
      },
    ],
  },
  {
    title: "Man Arrested for Writing False Restaurant Reviews",
    type: "2- Intermediate Texts",
    order: 101,
    // description:
    //   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
    image:
      "https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/4Ck3kSwo6fYQWDPDYqGeJJ.jpeg",
    elements: [
      {
        subtitle: "Practice Vocabulary",
        comments: "Vocabulário adicional para prática.",
        order: 0,
        grid: 2,
        type: "sentences",
        sentences: [
          { english: "Arrested", portuguese: "Preso(a)" },
          { english: "Reviews", portuguese: "Avaliações" },
          { english: "Denied", portuguese: "Negou" },
          { english: "Police", portuguese: "Polícia" },
          { english: "Score", portuguese: "Pontuação" },
          { english: "Customer", portuguese: "Cliente" },
          { english: "Reputation", portuguese: "Reputação" },
          { english: "Defamation", portuguese: "Difamação" },
          { english: "Guilty", portuguese: "Culpado(a)" },
          { english: "Tourist", portuguese: "Turista" },
          { english: "Released", portuguese: "Liberado(a)" },
        ],
      },
      {
        subtitle: "Text",
        order: 1,
        type: "text",
        text: "A British man has been arrested in Thailand for allegedly writing false negative reviews online.The man, who has been named only as Alexander, is said to have been unhappy with an Italian restaurant when it didn't let him walk through it to get to his apartment more quickly.With the help of friends, he then allegedly left a large number of false one-star reviews about the restaurant.The 21-year-old denied this when he was spoken to by Thai police. The restaurant, which is on the popular holiday island of Phuket, saw its Google review score fall from 4.9 to 3.1. Alexander had wanted to walk through the restaurant to get home, but the restaurant didn't let him because he wasn't a customer.This happened in 2022, when Alexander was living in Phuket. But he was only arrested in Thailand's capital, Bangkok, in May this year.The restaurant said the bad reviews affected its finances and reputation.Thailand takes defamation very seriously. If Alexander is found guilty, he could be sent to prison for up to two years.If he doesn't want to go to prison, The Telegraph wrote, Alexander will have to show that the reviews he wrote are true.This isn't the first time something like this has happened in Thailand. In 2020, an American tourist was arrested after posting a negative review of a hotel on TripAdvisor.The tourist was later released after saying sorry.",
      },
      {
        subtitle: "Questions",
        comments: "Answer the questions below.",
        order: 2,
        type: "exercise",
        items: [
          "Why was the man allegedly unhappy with the restaurant?",
          " What did the restaurant's Google review score fall to?",
          "What punishment could Alexander face if found guilty?",
          "What are your thoughts on the man being arrested for writing false reviews?",
          "Do you think a two-year prison sentence is a fair punishment for what he did?",
          "Have you ever left a negative review online? What were you unhappy with?",
          "Do you think social media has made it easier or harder for businesses to manage their reputations?",
          "How important are online reviews to you when choosing a restaurant or hotel?",
        ],
      },
    ],
  },

  {
    title: "Life Expectancy Could Increase 5 Years by 2050",
    type: "2- Intermediate Texts",
    order: 102,
    // description:
    //   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
    image:
      "https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/1ln7PwsSsqUJv0XKbKgzJc.jpeg",
    elements: [
      {
        subtitle: "Practice Vocabulary",
        comments: "Vocabulário adicional para prática.",
        order: 0,
        grid: 2,
        type: "sentences",
        sentences: [
          { english: "Life expectancy", portuguese: "Expectativa de vida" },
          { english: "Average", portuguese: "Média" },
          { english: "Researchers", portuguese: "Pesquisadores" },
          { english: "Public health", portuguese: "Saúde pública" },
          {
            english: "Communicable diseases",
            portuguese: "Doenças transmissíveis",
          },
          {
            english: "Non-communicable diseases",
            portuguese: "Doenças não transmissíveis",
          },
          { english: "Heart disease", portuguese: "Doença cardíaca" },
          { english: "Cancer", portuguese: "Câncer" },
          { english: "Diabetes", portuguese: "Diabetes" },
          { english: "High blood pressure", portuguese: "Pressão alta" },
          { english: "High blood sugar", portuguese: "Açúcar alto no sangue" },
          { english: "Obesity", portuguese: "Obesidade" },
          {
            english: "Healthy life expectancy",
            portuguese: "Expectativa de vida saudável",
          },
          {
            english: "Health inequalities",
            portuguese: "Desigualdades de saúde",
          },
        ],
      },
      {
        subtitle: "Text",
        order: 1,
        type: "text",
        text: "Global life expectancy could increase by almost five years by 2050, but people may spend more time living with poor health. That's according to a new study published in The Lancet this May. The Global Burden of Disease Study 2021 found that life expectancies in some of the world's poorer countries could catch up to those in more developed countries. The study predicted that by 2050, global life expectancy will increase by 4.9 years for men and 4.2 years for women. Women are still predicted to have longer life expectancies, with a global average of 80.5 years, compared to 76.2 for men. The biggest increases are expected to come in sub-Saharan Africa. The researchers said improved public health measures have increased life expectancies. People are now more likely to survive things like communicable diseases and diseases suffered by new mothers and babies. However, it's not all good news. People are also expected to be affected by more non-communicable diseases, such as heart disease, cancer and diabetes. According to the study, the total number of years lost due to things like high blood pressure, high blood sugar and obesity has increased by almost 50% since the year 2000. And the researchers suggest that, while total life expectancy will increase almost five years, healthy life expectancy — the number of years a person can expect to live in good health — will only increase by about 2.6 years. Health inequalities between the world's poorest and richest people will remain, but the gap is getting smaller, said one of the senior authors, Chris Murray from the University of Washington. Murray said the aim for governments across the world should be to influence lifestyle factors that affect life expectancies. In other words, governments should encourage people to do things like eat healthily and get regular exercise.",
      },
      {
        subtitle: "Questions",
        comments: "Answer the questions below.",
        order: 2,
        type: "exercise",
        items: [
          "What are your thoughts on the study's findings?",
          "What's the average life expectancy in your country?",
          "What do you think global life expectancy will be by 2075?",
          "Do you think your government is doing enough to increase or promote healthy life expectancy?",
          "In your opinion, what would be the ideal human lifespan?",
        ],
      },
    ],
  },
];
