export const textsCourse = [
// "type": "1- Basic Texts",
//My Wonderful Family
{
title: "My Wonderful Family",
type: "1- Basic Texts",
order: 1,
image: "https://cf.ltkcdn.net/family/images/std/200821-800x533r1-family.jpg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Family", portuguese: "Família" },
{ english: "House", portuguese: "Casa" },
{ english: "Mountains", portuguese: "Montanhas" },
{ english: "Brother", portuguese: "Irmão" },
{ english: "Sister", portuguese: "Irmã" },
{ english: "Father", portuguese: "Pai" },
{ english: "Mother", portuguese: "Mãe" },
{ english: "Teacher", portuguese: "Professor" },
{ english: "Nurse", portuguese: "Enfermeira" },
{ english: "Hospital", portuguese: "Hospital" },
{ english: "Smart", portuguese: "Inteligente" },
{ english: "Nervous", portuguese: "Nervosa" },
{ english: "Kind", portuguese: "Gentil" },
{ english: "Grandmother", portuguese: "Avó" },
{ english: "Italy", portuguese: "Itália" },
{ english: "Strong", portuguese: "Forte" },
{ english: "Cook", portuguese: "Cozinhar" },
{ english: "Important", portuguese: "Importante" },
{ english: "Weekend", portuguese: "Fim de semana" },
{ english: "Board game", portuguese: "Jogo de tabuleiro" },
],
},
{
subtitle: "Text",
order: 1,
type: "text",
text: "I live in a house near the mountains. I have two brothers and one sister, and I was born last. My father teaches mathematics, and my mother is a nurse at a big hospital. My brothers are very smart and work hard in school. My sister is a nervous girl, but she is very kind. My grandmother also lives with us. She came from Italy when I was two years old. She has grown old, but she is still very strong. She cooks the best food! My family is very important to me. We do lots of things together. My brothers and I like to go on long walks in the mountains. My sister likes to cook with my grandmother. On the weekends we all play board games together. We laugh and always have a good time. I love my family very much.",
},
{
subtitle: "Questions",
comments: "Tente responder estas perguntas usando o que você aprendeu.",
order: 2,
type: "exercise",
items: [
"How many siblings does the author have?",
"What does the author's father do for a living?",
"Where did the grandmother come from?",
"What do the author and their brothers like to do together?",
"Who likes to cook with the grandmother?",
"What do they do on the weekends?",
"How does the author describe their sister?",
"Why is the family important to the author?",
],
},
],
},
//  "title": "Our Vacation",
{
title: "Our Vacation",
type: "1- Basic Texts",
order: 2,
image: "https://www.tcbrasil.com.br/wp-content/uploads/2021/12/Saiba-se-Vacation-Club-vale-a-pena-para-o-seu-negocio.jpg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Vacation", portuguese: "Férias" },
{ english: "Beach", portuguese: "Praia" },
{ english: "Sand", portuguese: "Areia" },
{ english: "Palm tree", portuguese: "Palmeira" },
{ english: "Beautiful", portuguese: "Bonito" },
{ english: "Sandcastle", portuguese: "Castelo de areia" },
{ english: "Sailboat", portuguese: "Veleiro" },
{ english: "Dolphin", portuguese: "Golfinho" },
{ english: "Whale", portuguese: "Baleia" },
{ english: "Shell", portuguese: "Concha" },
{ english: "Surf", portuguese: "Surfar" },
{ english: "Fun", portuguese: "Divertido" },
{ english: "Learn", portuguese: "Aprender" },
{ english: "Teach", portuguese: "Ensinar" },
],
},
{
subtitle: "Text",
order: 1,
type: "text",
text: "Every year we go to Florida. We like to go to the beach. My favorite beach is called Emerson Beach. It is very long, with soft sand and palm trees. It is very beautiful. I like to make sandcastles and watch the sailboats go by. Sometimes there are dolphins and whales in the water! Every morning we look for shells in the sand. I found fifteen big shells last year. I put them in a special place in my room. This year I want to learn to surf. It is hard to surf, but so much fun! My sister is a good surfer. She says that she can teach me. I hope I can do it!",
},
{
subtitle: "Questions",
comments: "Tente responder estas perguntas usando o que você aprendeu.",
order: 2,
type: "exercise",
items: [
"Where does the author go every year?",
"What is the name of the author's favorite beach?",
"What does the author like to do at the beach?",
"What kind of animals does the author sometimes see in the water?",
"How many shells did the author find last year?",
"Where did the author put the shells?",
"What does the author want to learn this year?",
"Who is good at surfing in the author's family?",
"What does the sister say she can do for the author?",
],
},
],
},
// "title": "Preparing Food",
{
title: "Preparing Food",
type: "1- Basic Texts",
order: 3,
image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Hungry", portuguese: "Com fome" },
{ english: "Kitchen", portuguese: "Cozinha" },
{ english: "Egg", portuguese: "Ovo" },
{ english: "Oil", portuguese: "Óleo" },
{ english: "Skillet", portuguese: "Frigideira" },
{ english: "Stove", portuguese: "Fogão" },
{ english: "Heat", portuguese: "Calor" },
{ english: "Bowl", portuguese: "Tigela" },
{ english: "Stir", portuguese: "Mexer" },
{ english: "Cook", portuguese: "Cozinhar" },
{ english: "Plate", portuguese: "Prato" },
{ english: "Dining room", portuguese: "Sala de jantar" },
{ english: "Chair", portuguese: "Cadeira" },
{ english: "Spoon", portuguese: "Colher" },
{ english: "Soap", portuguese: "Sabão" },
{ english: "Sponge", portuguese: "Esponja" },
{ english: "Damp", portuguese: "Úmido" },
{ english: "Wipe", portuguese: "Limpar" },
{ english: "Table", portuguese: "Mesa" },
{ english: "Watch", portuguese: "Assistir" },
],
},
{
subtitle: "Text",
order: 1,
type: "text",
text: "Jack was hungry. He walked to the kitchen. He got out some eggs. He took out some oil. He placed a skillet on the stove. Next, he turned on the heat. He poured the oil into the skillet. He cracked the eggs into a bowl. He stirred the eggs. Then, he poured them into the hot skillet. He waited while the eggs cooked. They cooked for two minutes. He heard them cooking. They popped in the oil. Next, Jack put the eggs on a plate. He placed the plate on the dining room table. They looked pretty on the white plate. He sat down in the large wooden chair. He thought about the day ahead. He ate the eggs with a spoon. They were good. He washed the plate with dishwashing soap. Then, he washed the pan. He got a sponge damp. Finally, he wiped down the table. Next, Jack watched TV.",
},
{
subtitle: "Questions",
comments: "Tente responder estas perguntas usando o que você aprendeu.",
order: 2,
type: "exercise",
items: [
"Why did Jack go to the kitchen?",
"What did Jack do first after getting to the kitchen?",
"How long did the eggs cook?",
"What did Jack do after cooking the eggs?",
"What did Jack think about while eating?",
"What did Jack do after eating?",
"How did Jack clean the table?",
"What did Jack do after cleaning the table?",
"What did Jack use to eat the eggs?",
],
},
],
},
//  type: "2- Intermediate Texts",
//  title: "Saudi Money Helps Make Ronaldo Top Earning Athlete",
{
title: "Saudi Money Helps Make Ronaldo Top Earning Athlete",
type: "2- Intermediate Texts",
order: 0,
// description:
//   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
image:
"https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/7iYuXO0RUVscpjGZnDJfCH.jpeg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Athlete", portuguese: "Atleta" },
{ english: "Career", portuguese: "Carreira" },
{ english: "Magazine", portuguese: "Revista" },
{ english: "Soccer", portuguese: "Futebol" },
{ english: "To Earn", portuguese: "Ganhar/Render" },
{ english: "Earnings", portuguese: "Ganhos" },
{ english: "Tour", portuguese: "Turnê" },
{ english: "Money", portuguese: "Dinheiro" },
{ english: "Player", portuguese: "Jogador" },
{ english: "Reputation", portuguese: "Reputação" },
{ english: "Rival", portuguese: "Rival" },
],
},
{
subtitle: "Questions",
comments: "Tente responder estas pergunta usando o que você aprendeu.",
order: 2,
type: "exercise",
items: [
"What are your thoughts on Forbes' list of highest-paid athletes?",
"Are you a fan of Cristiano Ronaldo? Do you find it surprising that he's the world's highest-paid athlete?",
"Do you think professional athletes are paid too much?",
"Who do you imagine are your country's highest-paid athletes?",
"Which of the athletes mentioned in the article would you most like to meet?",
"Are you more into soccer, golf, or basketball?",
"In your opinion, who are the greatest athletes of all time?",
"Are there any famous athletes that you dislike?",
"What do you imagine are the hardest things about being a professional athlete?",
"If you don't believe you are the best, then you will never achieve all that you are capable of. — Cristiano Ronaldo. What do you make of this quote?",
],
},
],
},
// title: "Man Arrested for Writing False Restaurant Reviews",
{
title: "Man Arrested for Writing False Restaurant Reviews",
type: "2- Intermediate Texts",
order: 2,
// description:
//   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
image:
"https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/4Ck3kSwo6fYQWDPDYqGeJJ.jpeg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Arrested", portuguese: "Preso(a)" },
{ english: "Reviews", portuguese: "Avaliações" },
{ english: "Denied", portuguese: "Negou" },
{ english: "Police", portuguese: "Polícia" },
{ english: "Score", portuguese: "Pontuação" },
{ english: "Customer", portuguese: "Cliente" },
{ english: "Reputation", portuguese: "Reputação" },
{ english: "Defamation", portuguese: "Difamação" },
{ english: "Guilty", portuguese: "Culpado(a)" },
{ english: "Tourist", portuguese: "Turista" },
{ english: "Released", portuguese: "Liberado(a)" },
],
},
{
subtitle: "Text",
order: 1,
type: "text",
text: "A British man has been arrested in Thailand for allegedly writing false negative reviews online.The man, who has been named only as Alexander, is said to have been unhappy with an Italian restaurant when it didn't let him walk through it to get to his apartment more quickly.With the help of friends, he then allegedly left a large number of false one-star reviews about the restaurant.The 21-year-old denied this when he was spoken to by Thai police. The restaurant, which is on the popular holiday island of Phuket, saw its Google review score fall from 4.9 to 3.1. Alexander had wanted to walk through the restaurant to get home, but the restaurant didn't let him because he wasn't a customer.This happened in 2022, when Alexander was living in Phuket. But he was only arrested in Thailand's capital, Bangkok, in May this year.The restaurant said the bad reviews affected its finances and reputation.Thailand takes defamation very seriously. If Alexander is found guilty, he could be sent to prison for up to two years.If he doesn't want to go to prison, The Telegraph wrote, Alexander will have to show that the reviews he wrote are true.This isn't the first time something like this has happened in Thailand. In 2020, an American tourist was arrested after posting a negative review of a hotel on TripAdvisor.The tourist was later released after saying sorry.",
},
{
subtitle: "Questions",
comments: "Answer the questions below.",
order: 2,
type: "exercise",
items: [
"Why was the man allegedly unhappy with the restaurant?",
" What did the restaurant's Google review score fall to?",
"What punishment could Alexander face if found guilty?",
"What are your thoughts on the man being arrested for writing false reviews?",
"Do you think a two-year prison sentence is a fair punishment for what he did?",
"Have you ever left a negative review online? What were you unhappy with?",
"Do you think social media has made it easier or harder for businesses to manage their reputations?",
"How important are online reviews to you when choosing a restaurant or hotel?",
],
},
],
},
// title: "Life Expectancy Could Increase 5 Years by 2050",
{
title: "Life Expectancy Could Increase 5 Years by 2050",
type: "2- Intermediate Texts",
order: 102,
// description:
//   "Quando falamos sobre 'ter', no sentido de 'haver' ou 'existir', usamos, no presente, as expressões THERE IS e THERE ARE.",
image:
"https://transcode-v2.app.engoo.com/image/fetch/f_auto,c_lfill,w_600,dpr_1/https://assets.app.engoo.com/organizations/5d2656f1-9162-461d-88c7-b2505623d8cb/images/1ln7PwsSsqUJv0XKbKgzJc.jpeg",
elements: [
{
subtitle: "Practice Vocabulary",
comments: "Vocabulário adicional para prática.",
order: 0,
grid: 2,
type: "sentences",
sentences: [
{ english: "Life expectancy", portuguese: "Expectativa de vida" },
{ english: "Average", portuguese: "Média" },
{ english: "Researchers", portuguese: "Pesquisadores" },
{ english: "Public health", portuguese: "Saúde pública" },
{
english: "Communicable diseases",
portuguese: "Doenças transmissíveis",
},
{
english: "Non-communicable diseases",
portuguese: "Doenças não transmissíveis",
},
{ english: "Heart disease", portuguese: "Doença cardíaca" },
{ english: "Cancer", portuguese: "Câncer" },
{ english: "Diabetes", portuguese: "Diabetes" },
{ english: "High blood pressure", portuguese: "Pressão alta" },
{ english: "High blood sugar", portuguese: "Açúcar alto no sangue" },
{ english: "Obesity", portuguese: "Obesidade" },
{
english: "Healthy life expectancy",
portuguese: "Expectativa de vida saudável",
},
{
english: "Health inequalities",
portuguese: "Desigualdades de saúde",
},
],
},
{
subtitle: "Text",
order: 1,
type: "text",
text: "Global life expectancy could increase by almost five years by 2050, but people may spend more time living with poor health. That's according to a new study published in The Lancet this May. The Global Burden of Disease Study 2021 found that life expectancies in some of the world's poorer countries could catch up to those in more developed countries. The study predicted that by 2050, global life expectancy will increase by 4.9 years for men and 4.2 years for women. Women are still predicted to have longer life expectancies, with a global average of 80.5 years, compared to 76.2 for men. The biggest increases are expected to come in sub-Saharan Africa. The researchers said improved public health measures have increased life expectancies. People are now more likely to survive things like communicable diseases and diseases suffered by new mothers and babies. However, it's not all good news. People are also expected to be affected by more non-communicable diseases, such as heart disease, cancer and diabetes. According to the study, the total number of years lost due to things like high blood pressure, high blood sugar and obesity has increased by almost 50% since the year 2000. And the researchers suggest that, while total life expectancy will increase almost five years, healthy life expectancy — the number of years a person can expect to live in good health — will only increase by about 2.6 years. Health inequalities between the world's poorest and richest people will remain, but the gap is getting smaller, said one of the senior authors, Chris Murray from the University of Washington. Murray said the aim for governments across the world should be to influence lifestyle factors that affect life expectancies. In other words, governments should encourage people to do things like eat healthily and get regular exercise.",
},
{
subtitle: "Questions",
comments: "Answer the questions below.",
order: 2,
type: "exercise",
items: [
"What are your thoughts on the study's findings?",
"What's the average life expectancy in your country?",
"What do you think global life expectancy will be by 2075?",
"Do you think your government is doing enough to increase or promote healthy life expectancy?",
"In your opinion, what would be the ideal human lifespan?",
],
},
],
},
];
