export const buttons = [
  {
    color: "green",
    score: 550,
    description: "Revisou o Anki 6 dias em 7",
    category: "Anki",
    text: "Anki 6/7",
  },
  {
    color: "green",
    score: 215,
    description: "Revisou o Anki 3 dias em 7",
    category: "Anki",
    text: "Anki 3/7",
  },
  {
    color: "green",
    score: 80,
    description: "Zerou o Anki e mandou foto",
    category: "Anki",
    text: "Zerou o Anki e mandou foto",
  },
  {
    color: "green",
    score: 750,
    description: "Apresentação na aula ao vivo",
    category: "Live Class",
    text: "Apresentação na aula ao vivo",
  },
  {
    color: "green",
    score: 35,
    description: "Fez Stories fazendo o Anki",
    category: "Anki",
    text: "Fez Stories fazendo o Anki",
  },
  {
    color: "green",
    score: 120,
    description: "Chegou com o Anki totalmente revisado",
    category: "Anki",
    text: "Chegou com o Anki totalmente revisado",
  },
  {
    color: "green",
    score: 575,
    description: "Fez homework",
    category: "Homework",
    text: "Fez homework",
  },
  {
    color: "green",
    score: 85,
    description: "Recomendação fechada",
    category: "Others",
    text: "Recomendação fechada",
  },
  {
    color: "green",
    score: 80,
    description: "Participou da aula ao vivo",
    category: "Live Class",
    text: "Live Class Attendance",
  },
  {
    color: "green",
    score: 500,
    description: "Fez o Homework da aula ao vivo",
    category: "Live Class",
    text: "Live Class Homework",
  },
  {
    color: "red",
    score: -75,
    description: "Não apareceu para a aula e não avisou",
    category: "Awol",
    text: "AWOL",
  },
];
