export const buttons = [
  {
    color: "green",
    score: 500,
    description: "Revisou o Anki 6 dias em 7",
    category: "Anki",
    text: "Anki 6/7",
  },
  {
    color: "green",
    score: 200,
    description: "Revisou o Anki 3 dias em 7",
    category: "Anki",
    text: "Anki 3/7",
  },
  {
    color: "green",
    score: 100,
    description: "Zerou o Anki e mandou foto",
    category: "Anki",
    text: "Zerou o Anki e mandou foto",
  },
  {
    color: "green",
    score: 100,
    description: "Fez Stories fazendo o Anki",
    category: "Anki",
    text: "Fez Stories fazendo o Anki",
  },
  {
    color: "green",
    score: 100,
    description: "Fez Stories fazendo Homework",
    category: "Anki",
    text: "Fez Stories fazendo Homework",
  },
  {
    color: "red",
    score: -100,
    description: "Não revisou o Anki em 7 dias",
    category: "Anki",
    text: "Nenhum Anki Review na semana",
  },
  {
    color: "green",
    score: 200,
    description: "Chegou com o Anki totalmente revisado",
    category: "Anki",
    text: "Chegou com o Anki totalmente revisado",
  },
  {
    color: "green",
    score: 500,
    description: "Fez homework",
    category: "Homework",
    text: "Fez homework",
  },
  {
    color: "green",
    score: 300,
    description: "Recomendação fechada",
    category: "Others",
    text: "Recomendação fechada",
  },
  {
    color: "green",
    score: 300,
    description: "Participou da aula ao vivo",
    category: "Live Class",
    text: "Live Class Attendance",
  },
  {
    color: "green",
    score: 500,
    description: "Fez o Homework da aula ao vivo",
    category: "Live Class",
    text: "Live Class Homework",
  },
  {
    color: "red",
    score: -200,
    description: "Não apareceu para a aula e não avisou",
    category: "Awol",
    text: "AWOL",
  },
];
